### ISSUE TITLE
Any news?

### ISSUE THREAD

**Issue by SilverioMiranda** [microsoft/kiota-serialization-multipart-dotnet#1]
When are you going to start this project?

**Comment by baywet** [comment]
Thank you for the patience on the late reply. I wasn't subscribed to the repo and didn't get a notification.

Progress is being shared on https://github.com/microsoft/kiota/issues/220

We're almost wrapped up for request body serialization, and we're not doing response body deserialization for the time being as it seems that this is not something that APIs use in general. We're working on publishing the libraries in Java/Go/Dotnet/TypeScript before we merge and release the generation changes. Hopefully everything will be wrapped up in a couple of days.
